version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    
  frontend:
    build:
      context: /home/adam/Desktop/voice-recorder/
      dockerfile: /home/adam/Desktop/voice-recorder/Dockerfile
    command: npm start
    volumes:
      - /home/adam/Desktop/voice-recorder/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web

