# Generated by Django 3.2 on 2023-09-04 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recorder', '0004_auto_20230821_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 4, 15, 48, 25, 311229)),
        ),
        migrations.AlterField(
            model_name='recordgroup',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 4, 15, 48, 25, 311776)),
        ),
    ]
