# Generated by Django 3.2 on 2023-05-23 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recorder', '0006_auto_20230523_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 23, 23, 59, 56, 983461)),
        ),
        migrations.AlterField(
            model_name='recordgroup',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 23, 23, 59, 56, 983818)),
        ),
    ]
