# Generated by Django 3.2 on 2023-05-25 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recorder', '0007_auto_20230523_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voice_recorder.author'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voice_recorder.recordgroup'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 25, 14, 29, 6, 297669)),
        ),
        migrations.AlterField(
            model_name='recordgroup',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 25, 14, 29, 6, 298742)),
        ),
    ]
