# Generated by Django 3.2 on 2023-09-05 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recorder', '0008_auto_20230821_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 5, 12, 23, 37, 992759)),
        ),
        migrations.AlterField(
            model_name='recordgroup',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 9, 5, 12, 23, 37, 993899)),
        ),
    ]
